[profile.default]
src = "src"
out = "out"
libs = ["lib"]

fs_permissions = [
    { access = "read-write", path = "./deployments" },
    { access = "read", path = "./" },
]

[rpc_endpoints]
  gnosis = "${GNOSIS_RPC_URL}"
  sepolia = "${SEPOLIA_RPC_URL}"
  polygon = "${POLYGON_RPC_URL}"
  optimism = "${OPTIMISM_RPC_URL}"
  base = "${BASE_RPC_URL}"
  anvil = "http://127.0.0.1:8545"

[etherscan]
  arbitrum = { key = "${ARBISCAN_API_KEY}" }
  mainnet = { key = "${ETHERSCAN_API_KEY}" }
  optimism = { key = "${OPTIMISTIC_ETHERSCAN_API_KEY}" }
  polygon = { key = "${POLYGONSCAN_API_KEY}", url = "https://api.polygonscan.com/api/" }
  sepolia = { key = "${ETHERSCAN_API_KEY}" }
  gnosis = { key = "${GNOSISSCAN_API_KEY}", url = "https://api.gnosisscan.io/api/" }
  base = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api/" }

